force-app/main/default/objects/Key_Result__c/Key_Result__c.object-meta.xml
<CustomObject>
    <label>Key Result</label>
    <nameField>
        <label>Key Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Key Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Result__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Master Detail relationship with Objective being parent and child being Key_Result</description>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Key Results</relationshipLabel>
    <relationshipName>Key_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Field &quot;Year&quot; for object &quot;Objective&quot;. Picklist with possibility to choose one of 4 years: 2024, 2025, 2026 or 2027</description>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/okrDashboardController.cls
public with sharing class okrDashboardController {

    @AuraEnabled(cacheable=true)
    public static List<Objective__c> getObjectives(Integer year, Id userId) {
        try {
            return [SELECT Id, Name, Year__c FROM Objective__c
                    WHERE Year__c =: year
                    AND OwnerId =: userId];
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    @AuraEnabled(cacheable=true)
    public static List<User> getUsers() {
        try {
            return [SELECT Id, Name FROM User];
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Key_Result__c> getKeyResults(Id objectiveId) {
        try {
            return [SELECT Id, Name, Objective__c FROM Key_Result__c
                    WHERE Objective__c =: objectiveId];
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}